- name: Install docker and gitlab
  hosts: all
  become: true
  vars:
    gitlab_home: /srv/gitlab
  roles:
    - role: geerlingguy.docker
      tags:
        - install
  tasks:
    - name: mkdir /opt/gitlab
      file:
        state: directory
        path: /opt/gitlab
        owner: user
        group: user
        mode: "0755"
      tags:
        - copy
    - name: Copy gitlab docker-compose.yml
      copy:
        src: ./files/gitlab/docker-compose.yml
        dest: /opt/gitlab/docker-compose.yml
        owner: user
        group: user
        mode: "0755"
      tags:
        - copy
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - gitlab
    - name: Install pip
      apt:
        name:
          - python3-pip
      tags:
        - gitlab
    - name: Install Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose
      tags:
        - gitlab
    - name: mkdir gitlab home
      file:
        state: directory
        path: "{{ gitlab_home }}"
        owner: user
        group: user
        mode: "0755"
      tags:
        - gitlab
    - name: Run gitlab docker compose
      docker_compose:
        project_src: /opt/gitlab
      environment:
        GITLAB_HOME: "{{ gitlab_home }}"
      tags:
        - gitlab

